# Generated by Django 3.1.7 on 2021-03-04 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210304_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.listing'),
            preserve_default=False,
        ),
    ]
